apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-volume
  namespace: default
  labels:
    app: weblog
    type: storage
spec:
  storageClassName: slow
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/data/storage"
    type: Directory


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-claim
  namespace: default
  labels:
    app: weblog
    type: storage
spec:
  storageClassName: slow
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: default
  labels:
    app: weblog
    type: database
type: Opaque
data:
  root_username: YWRtaW4=
  root_password: UGFzc3cwcmQ=
  keyfile: ZGdQeGxNVkYvR0g1RzdLTDcvUllkTVdFcUxXZEExdDZBK1R3Q0NSR0hPbWZDZXdLSHlPdWp1MXlPZkl6VndETmNOV2laa0ZQVTRvNjUwTnRyRUxOOGVSOHJISTJFSDlob1hOMWY4dytXY3dlUm0rWGNhbGptVTRjbzVyOEhta3ZVMEk3RGVraUtWRkpYQzhidmU4MXhyWC80WW1pQUdvb2Z0SjA4SlZGaGJJRDZiZlk0L1pwNXRaNzJtWVZUV2g4dkVXMEhSRTdRN1RNQVI3NE9tREJZNENEVmFZNDFkQnBFYTFqZWtiL2wvREJFQjRnUXdqcGl0YkZrcjA1ekFGUE9oTk9GTGVFZ1RMU05nZHNHOVFoeHJQeGhQY1B3YnlUN3ppMjdBa2ZBM3hWbVIzYy95RTE5eG42OG5tMUEzL2JuaC9hZlVrMEluc3dwU1M1V0pzSFpHSnUyNStWRUR6Y24xSjU2K1lUQWc4bzl2N1B2dm04T2I2cktXK2YxVHordHdVTzc0cUZxQ3diR0p2VVJNY3RuS3hYb2NHU1R4R1hFSW5LY0xXTjZTWU5VSHRXSW9SQTBUK1ZtMU5yV0x6RFFNdEwrY2NxRzdkOFkvOWJ3QUltaGlNQVBTb2ZCMmJrSmt1Nk1kMWtWTFBQcUJocng1MWRkQmpWdG42VGlHUytUNDRkZWV0VWxreDI5M0M0Njl3WFhkU0dBWXpGQkZnNktiZ0N3NnU2SXBmaS80bjdjaWM4MWFrS3RQeXd0M25KdVhIS2MyZTgvUWpIajEvSkxma3NtazFPYUxNekRFbTM1Q2JJV2lOVHlQZGZNd0NlNXpnRGQ0WUFseCs2YmVJU2toNU1mVmN0U0kxNGE4cWd2TEt4UDBtTFEzdEJwY1RIMnFoV0VaakVKUTM4SkVyalZXSlJCN1BCVmFzd0xNTGNiVzcrTkRtVWZ5RUFxeDUyYWFxY2ZLSmxFVlhtcHFhRFJVTXV5RlNCcU5lYlN1U3ZVUis0Q293ank3NW14ZCt6cHFhcDBjQ2FEdW9Wd1docUJKS1ZQZ2YzWVJCS1NPdEwrYytUbWsra2lrM3lqQ2h6RjMySFNydy91ditEVWhyOUdoSVVGbkxiekIxbXhEV1I3UkRFaktNQUhodUJVZm1RMUZjbEY1dktUT3hYMlE4RXZaTndBak1zQ1VUSnF1Z2Exb001dmQ5Z2hsWDFsUTkwb3EvaTl0aXlaKzZDK3BpTXFyRysyci8vNVdTRW1aWjVBRURMRzVOSjI1MDJSK2xYdmRuc0t1N0pDNHc2Y0JvWEdXVXVqVjRQMEtIdElrYUdoeVNGUjNHT09uYWNFRWZ1K2dqcE1sRzJVUkRTcElSeAo=

---

apiVersion: v1
kind: Pod
metadata:
  name: mondodb
  namespace: default
  labels:
    app: weblog
    type: database
spec:
  containers:
  - name: mongodb
    image: weblog-db:v1.0.0
    imagePullPolicy: Never
    args: 
    - "mongod"
    - "--auth"
    - "--bind_ip_all"
    env:
    - name: "MONGO_INITDB_ROOT_USERNAME"
      valueFrom:
        secretKeyRef:
          name: mongo-secret
          key: root_username
    - name: "MONGO_INITDB_ROOT_DATABASE"
      value: "admin"
      valueFrom:
        secretKeyRef:
          name: mongo-secret
          key: root_password
    volumeMounts:
    - mountPath: /data/db
      name: storage
    - mountPath: /home/mongodb
      name: secret
  volumes:
  - name: storage
    PersistentVolumeClaim:
      claimName: storage-claim
  - name: secret
    secret:
      secretName: mongo-secret
      items:
      - key: keyfile
        name: keyfile
        mode: 0700